--- # -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# Site settings
author: CPSC 4880/5880 Staff
name: CPSC 4880/5880
title: Advances in Frontier AI Models
email: arman.cohan@yale.edu
description: >
  Advances in Frontier AI Models, Yale University, Fall 2026
footer_text: >
  Powered by <a href="http://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a>
  <br/>Theme based on <a href="https://github.com/cmudeeprl"> CMU Deep RL</a>.

url: # the base hostname & protocol for your site
baseurl: # the subpath of your site, e.g. /blog/

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------
github_username: armancohan
google_analytics:
youtube_channel:
twitter_username: armancohan

# Optional features
enable_anchorjs: true

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
highlighter: rouge

# Includes & excludes
include: ["_pages"]
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

# Plug-ins
plugins:
  - jekyll-email-protect

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
anchorjs_version: "3.2.2"
